// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/wangchengkun/Documents/ajaxlinux1234.github.io/src/pages/im/models/channels';
import model_2 from '/Users/wangchengkun/Documents/ajaxlinux1234.github.io/src/pages/im/models/global';
import model_3 from '/Users/wangchengkun/Documents/ajaxlinux1234.github.io/src/pages/im/models/login';
import model_4 from '/Users/wangchengkun/Documents/ajaxlinux1234.github.io/src/pages/im/models/member';
import model_5 from '/Users/wangchengkun/Documents/ajaxlinux1234.github.io/src/pages/im/models/message';
import model_6 from '/Users/wangchengkun/Documents/ajaxlinux1234.github.io/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'im.channels', model: model_1 },
model_2: { namespace: 'im.global', model: model_2 },
model_3: { namespace: 'im.login', model: model_3 },
model_4: { namespace: 'im.member', model: model_4 },
model_5: { namespace: 'im.message', model: model_5 },
model_6: { namespace: '@@initialState', model: model_6 },
} as const
