// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/wangchengkun/Documents/ajaxlinux1234.github.io/src/pages/im/models/member';
import model_2 from '/Users/wangchengkun/Documents/ajaxlinux1234.github.io/src/pages/im/models/message';
import model_3 from '/Users/wangchengkun/Documents/ajaxlinux1234.github.io/src/.umi-production/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'im.member', model: model_1 },
model_2: { namespace: 'im.message', model: model_2 },
model_3: { namespace: '@@initialState', model: model_3 },
} as const
